
export const accessories = [

{
rep: 1,
made: "ORAIMO",
owner: "MEMORY CARD",
photo: "img/oraimo-8.png",
size: " SIZE: 8GB",
amount: "2500 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 2,
made: "SAN DISK",
owner: "MEMORY CARD",
photo: "img/sandisk-8.jpg",
size: " SIZE: 8GB",
amount: "2500 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 3,
made: "SAN DISK",
owner: "MEMORY CARD",
photo: "img/sandisk-16.jpg",
size: " SIZE: 16GB",
amount: "3000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 4,
made: "SAN DISK",
owner: "MEMORY CARD",
photo: "img/sandisk-32.jpg",
size: " SIZE: 32GB",
amount: "3500 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 5,
made: "SAN DISK",
owner: "MEMORY CARD",
photo: "img/sandisk-64.jpg",
size: " SIZE: 64GB",
amount: "5500 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 6,
made: "SAN DISK",
owner: "MEMORY CARD",
photo: "img/sandisk-128.jpg",
size: " SIZE: 128GB",
amount: "9000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 7,
made: "NEW AGE",
owner: "POWER BANK",
photo: "img/y29.png",
version: " MODEL: Y29",
btty: " BATTERY: 15600 mAh",
amount: "8000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 8,
made: "NEW AGE",
owner: "POWER BANK",
photo: "img/y305.jpg",
version: " MODEL: Y305",
btty: " BATTERY: 12500mAh",
amount: "6000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 9,
made: "NEW AGE",
owner: "POWER BANK",
photo: "img/y3-2c.png",
version: " MODEL: Y3-2C",
btty: " BATTERY: 6500mAh",
amount: "3500 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 10,
made: "NEW AGE",
owner: "POWER BANK",
photo: "img/ck-02.jpg",
version: " MODEL: CK-02",
btty: " BATTERY: 22500mAh",
amount: "10000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 11,
made: "ORAIMO",
owner: "POWER BANK",
photo: "img/oraimo20000.jpg",
btty: " BATTERY: 20000mAh",
amount: "10000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 12,
made: "QLT CHOICE",
owner: "POWER BANK",
photo: "img/qlt-choice.jpg",
version: " MODEL: NSM-P12",
btty: " BATTERY: 12000mAh",
amount: "6800 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 13,
made: "VEGER",
owner: "POWER BANK",
photo: "img/veger.jpg",
version: " MODEL: X106 ULTIMATE",
btty: "BATTERY: 10000mAh",
amount: "6000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 14,
made: "LI-POLYMER",
owner: "POWER BANK",
photo: "img/li-polymer.jpeg",
btty: "BATTERY: 20000mAh",
amount: "9000 (NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 15,
made: "ORAIMO",
owner: "HEADPHONE",
photo: "img/oeb-e74d.jpg",
version: "MODEL: NECKLACE 2 0EB-E74D",
btty: "UP TO 310 BATTERY LIFE",
features: "SOUND IN MOTION, SWEAT PROOF, HD SOUND, ERGONOMIC NECKBAND, MAGNETIC BUDS",
amount: "10000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 16,
made: "ORAIMO",
owner: "HEADPHONE",
photo: "img/oeb-e54d.jpg",
version: "MODEL: NECKLACE 0EB-E54D",
btty: "UP TO 200 BATTERY LIFE",
features: " WEAR YOUR MUSIC, ANTI-LOSS, HD SOUND, ULTRA-LONG STANDBY, MAGNETIC BUDS",
amount: "9500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 17,
made: "ORAIMO",
owner: "HEADPHONE",
photo: "img/oeb-e57d.jpg",
version: "MODEL: SHARK 0EB-E57D",
btty: " ",
features: "SOUND MORE WIRE LESS, SWEAT PROOF, EXTREME BASS, ERGONOMIC NECKBAND, MAGNETIC BUDS",
amount: "8500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 18,
made: "ORAIMO",
owner: "WIRELESS HEADSET",
photo: "img/oeb-e36s.jpg",
version: "MODEL: ELITE 2 0EB-E36S",
btty: "300 HRS STANDBY ALL DAY TALK TIME",
features: "ULTIMATE COMFORT, WIRELESS, HD VOICE, ULTRA-LONG STANDBY",
amount: "4500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 19,
made: "ORAIMO",
owner: "WIRELESS HEADSET",
photo: "img/oeb-e32s.jpg",
version: "MODEL: KNIGHT 2 0EB-E32S",
btty: " ",
features: "STABLE CONNECTION, EASY TO USE, HD VOICE, WIRELESS HEADSET, ENERGY RELIABLE CALLING, SUPER LONG STANDBY",
amount: "5000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 20,
made: "ORAIMO",
owner: "BLUETOOTH",
photo: "img/obs-52d.jpg",
version: "MODEL: SOUND PRO (OBS-52D)",
btty: " ",
features: "WIRELESS, AUX INPUT, USB DRIVE, TF CARD, MICRO PHONE, FM RADIO,ENHANCED FM CONNECTIVITY, PORTABLE HANDLE, STEREO SOUND",
amount: "10000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 21,
made: "ORAIMO",
owner: "HEADPHONES",
photo: "img/oeb-e54d.jpg",
version: "MODEL: OEB-E54D",
btty: " UP TO 200 BATTERY LIFE",
features: "WEAR YOUR MUSIC, ANTI-LOSS, HD SOUND, ULTRA-LONG STANDBY, MAGNETIC BUDS ",
amount: "9500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 22,
made: "ORAIMO",
owner: "HEADPHONES",
photo: "img/oEB-E55d.jpg",
version: "MODEL: FEATHER (OED-E55D)",
btty: " UP TO 120 HRS BATTERY LIFE",
features: "TRUE FREEDOM OF MOVEMENT, STEREO, SECURE FIT, VOLUME CONTROL, LIGHTWEIGHT DESIGN",
amount: "6000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 23,
made: "ORAIMO",
owner: "WIRELESS HEADSET",
photo: "img/oeb-e33s.jpg",
version: "MODEL: ELFIN (0EB-E33S)",
btty: " ",
features: "WIRELESS HEADSET, LONG STANDBY, EASY TO USE, HD VOICE, COMPACT DESIGN",
amount: "4500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 24,
made: "ORAIMO",
owner: "AIRPODS",
photo: "img/oeb-e98d.jpg",
version: "MODEL: FREEPODS (OEB-E98D)",
btty: " ",
features: "TRUE WIRELESS HALF-IN-EARBUDS, ERGONOMIC BUDS, INSTANT CONNECTION, HIGH-FIDELITY, ONE- BUTTON CONTROLS, POWER CHARGING CASE",
amount: "11500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 25,
made: "ORAIMO",
owner: "CHARGER",
photo: "img/pe.jpg",
version: "MODEL: Pe 2.0+ QC 3.0",
btty: " ",
features: "FAST CHARGING ",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 26,
made: "ORAIMO",
owner: "EAR PIECE",
photo: "img/vortex.jpg",
version: "MODEL: VORTEX OEP-E23",
btty: " ",
features: "EXTRA BASS, SLEEK FINISH, WEAR RESISTANT, REMOTE CONTROL, SINGLE-BUTTON REMOTE ",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 27,
made: "ORAIMO",
owner: "CHARGER HEAD",
photo: "img/DUAL.jpg",
version: "MODEL: FIREFLY OCW-U61D",
btty: " ",
features: "DUAL USB, LED INDICATOR, 2X USB CHARGER-KIT",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 28,
made: "ORAIMO",
owner: "CHARGER HEAD",
photo: "img/KIT.png",
version: "MODEL: OCW-E32S + OCD-M103",
btty: " ",
features: "CHARGER KITS",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 29,
made: "ORAIMO",
owner: "CABLE",
photo: "img/2A.jpg",
version: "MODEL: CU-60ZR + CD-52BR",
btty: " ",
features: "CHARGER KIT, 2A FAST CHARGING",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 30,
made: "ZEALOT",
owner: "BLUETOOTH",
photo: "img/zealot-s8.jpg",
version: "MODEL: S8",
btty: " ",
features: "TOUCH PANEL WIRELESS SPEAKER, POWER BANK, PORTABLE, MUSIC & CALL",
amount: "9000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 31,
made: "ZEALOT",
owner: "EAR BUDS",
photo: "img/zealot-h19.jpg",
version: "MODEL: H19",
btty: " ",
features: "TWS WIRELESS EARPHONES, MUSIC PLAYER, CALL, STEREO",
amount: "6000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 32,
made: "ZEALOT",
owner: "BLUETOOTH",
photo: "img/zealot-s1.jpg",
version: "MODEL: S1",
btty: " ",
features: "OUTDOOR WIRELESS SPEAKER, HIGH-POWER OF 1W LED, MOBILE POWER, FLASHLIGHT",
amount: "5500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 33,
made: "MS-T18",
owner: "WIRELESS HEADSET",
photo: "img/ms-t18.jpg",
version: "MODEL: MS-T18",
btty: " ",
features: "SUPPORT TF CARD PLAY MODE, ACTIVE NOISE CANCELLATION WIRELESS, OVER-EAR HEAD PHONES,LUXURIOUS LIGHTWEIGHT MATERIALS",
amount: "4500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 34,
made: "JARBA",
owner: "EAR BUDS",
photo: "img/halofusion.jpg",
version: "MODEL: HALO FUSION",
btty: " ",
features: "WIRELESS BUDS, POWERFUL STEREO SOUNDS, SIMPLE ONE BUTTON CONTROL, CONVIENT WEARING STYLE",
amount: "3900(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 35,
made: "i9S",
owner: "AIRPODS",
photo: "img/i9s.jpg",
version: "MODEL: V5.0 +EDR",
btty: " 35MAH/250MAH",
features: "2-3HRS PLAYING TIME, 1-2HRS CHARGING TIME, 100HRS STANDBY",
amount: "6500(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 36,
made: "DONGLE",
owner: "WIFI",
photo: "img/donglewireless.jpg",
version: "3G/4G WIRELESS USB",
btty: " ",
features: " ",
amount: "4000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 37,
made: "4G/3G WIFI ROUTER",
owner: "WIFI",
photo: "img/wifirouter.jpg",
version: " ",
btty: "UP TO 9 USERS(8WIFI + 1 USB)",
features: "50mbps UPLOAD SPEED, DATA & SMS, 150/100mbps DOWNLOAD SPEED, LTE Cate4/Cate3/DC-HSPA+/HSPA+/HSPA/UMTS, EDGE/GPRS/GSM",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 38,
made: "T&G",
owner: "BLUETOOTH",
photo: "img/t-g.jpg",
version: " ",
btty: "6W (OUTPUT3W x 2RMS)",
features: " PORTABLE WIRELESS SPEAKER, HANDS-FREE PHONE CALL, RADIO",
amount: "6000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 39,
made: "SLC-061",
owner: "BLUETOOTH",
photo: "img/slc.jpg",
version: " ",
btty: "10000mAh with dual USB charge out",
features: "IPX7 WATERPROFF, SPEAKER, 12HOURS PLAYTIME",
amount: "5000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 40,
made: "H110",
owner: "HEADSET",
photo: "img/h110.jpg",
version: " ",
btty: "",
features: " STEREO HEADSET FOR COMPUTERS",
amount: "6000(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 41,
made: "INFINIX",
owner: "usb cable",
photo: "img/xpl.jpg",
version: " ",
btty: " (OUTPUT 5V x 2A)",
features: " MICRO USB CABLE, 1000MM-LENGTH",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 42,
made: "MINI KEYBOARD",
owner: "keyboard",
photo: "img/minikey.jpg",
version: " ",
btty: " ",
features: " MINI KEYBOARD K-1000, MAC+PC",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 43,
made: "QLT CHOICE",
owner: "mouse",
photo: "img/WM.jpg",
version: "MODEL: WM-12 ",
btty: " ",
features: " SILENT WIRELESS MOUSE, 15m LONG DISTANCE WIRELESS TRANSMISSION, HIGH PRECISION OPTICAL",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 44,
made: "QLT CHOICE",
owner: "HEADPHONE",
photo: "img/NSM.jpg",
version: " MODEL: NSM-500",
btty: " RATED POWER 15mW",
features: " STEREO HEADPHONE, SPEAKERS DIMENSION 40mm",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
},
{
rep: 45,
made: "QLT CHOICE",
owner: "mouse",
photo: "img/mouse.jpg",
version: "MODEL: NSM-M01 ",
btty: " ",
features: " WINDOW 7 & 8, USB PORT, OFFICE MOUSE",
amount: "(NEGOTIABLE)",
inCart: false,
count:0,
total:0
}

];
    
export const infoAccessories =     {
        rep: 1,
        made: "ORAIMO",
        owner: "MEMORY CARD",
        photo: "img/oraimo-8.png",
        size: " SIZE: 8GB",
        amount: "2500 (NEGOTIABLE)",
        inCart: false,
        count:0,
        total:0      
    }
