

export const storeProducts = [

    {
id:1,
title: "Samsung Galaxy A51",
img:"img/samsung-Galaxy-A51-2.jpg",
price: 125200,
company: "SAMSUNG",
Keyfeatures: " DISPLAY: 6.5inches FHD+(1080 x 2400)sAMOLED",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 48MP+12MP+5MP+5MP 32MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.1",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: On-screen fingerprint, c-type fast charging, bixby",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:2,
title: "SAMSUNG GALAXY A31",
img:"img/A31.jpg",
price:106100,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.4inches FHD + sAMOLED",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 48MP+8MP+5MP+5MP 20MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.0",
processor: " PROCESSOR: Octa-core (Dual 2.0 GHz + Hexa 1.7GHz)",
dimensions: " DIMENSION: 159.3 x 73.1 x 8.6 mm",
others: " OTHERS: On-screen fingerprint, c-type fast charging",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:3,
title: "SAMSUNG GALAXY A71",
img:"img/A71.jpg",
price:173200,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.7inches FHD+sAMOLED",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 64MP+12MP+5MP+5MP  32MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2",
processor: " PROCESSOR: Exynos 9611 (Dual 2.2GHz + Hexa 1.8GHz)",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: On-screen fingerprint, c-type fast charging, bixby",
battery: " BATTERY: 4500mAh",
inCart: false,
count:0,
total:0
},
{
id:4,
title: "SAMSUNG GALAXY A30s",
img:"img/A30s.jpg",
price:86000,
company: "SAMSUNG",
Keyfeatures:" DISPLAY: 6.4inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA:  25MP+8MP+5MP 16MP",
OS: "OPERATING SYSTEM: Android 9.0(pie), upgradable to Android 10, One UI 2.1",
processor: " PROCESSOR: Octa-core (2x1.8 GHz Cortex-A73 & 6x1.6 GHz Cortex-A53)",
dimensions: " DIMENSION: 158.5 x 74.7 x 7.8 mm",
others: " OTHERS: fingerprint, 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:5,
title: "SAMSUNG GALAXY A20s",
img:"img/A20s.jpg",
price:68900,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.5inches",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+5MP+5MP  32MP front",
OS: "OPERATING SYSTEM: Android 9.0(pie), upgradable to Android 10, One UI 2.0",
processor: " PROCESSOR: Octa-core 1.8 GHz Cortex-A53",
dimensions: " DIMENSION: 163.3 x 77.5 x 8 mm",
others: " OTHERS: fingerprint(rear-mounted), 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:6,
title: "SAMSUNG GALAXY M11",
img:"img/M11.jpg",
price:63800,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.4inches",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+5MP+2MP 8MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.0",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 161.4 x 73.6 x 9 mm",
others: " OTHERS: fingerprint(rear-mounted), 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:7,
title: "SAMSUNG GALAXY A10s",
img:"img/A10s.jpg",
price:54000,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.2inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP+2MP 8MP front",
OS: "OPERATING SYSTEM: Android 9.0(pie), upgradable to Android 10 One UI 2.0",
processor: " PROCESSOR: Octa_core @>)GHz Cortex_A53",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: fingerprint(rear-mounted), 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:8,
title: "SAMSUNG GALAXY A01",
img:"img/A01.jpg",
price:44000,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 5.7inches",
space: " MEMORY: 16GB 2GB RAM",
camera: " CAMERA: 16MP+2MP 8MP front",
OS: "OPERATING SYSTEM: Android 9.0(pie), upgradable to Android, One UI 2.0",
processor: " PROCESSOR: Octa-core 2.0GHz Cortex-A53",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: fingerprint(rear-mounted), microUSB 2.0",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:9,
title: "SAMSUNG GALAXY A11",
img:"img/A11.jpg",
price:58500,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.5inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP 13MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.0",
processor: " PROCESSOR: Octa-core (4x2.0 GHz Cortex-A55 & 4x2.0 GHz Cortex-A55)",
dimensions: " DIMENSION: 163.7 x 75.3 x 8.9 mm",
others: " OTHERS: fingerprint(rear-mounted), 2.0, Type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:10,
title: "SAMSUNG GALAXY A21S",
img:"img/A21s.jpg",
price:84000,
company: "SAMSUNG",
Keyfeatures:"DISPLAY: 6.5inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP 13MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.0",
processor: " PROCESSOR: Octa-core (4x2.0 GHz Cortex-A55 & 4x2.0 GHz Cortex-A55)",
dimensions: " DIMENSION: 163.7 x 75.3 x 8.9 mm",
others: " OTHERS: fingerprint(rear-mounted), 2.0, Type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:11,
title: " TECNO F1",
img:"img/tecno-f1.jpg",
price:20500,
company: "TECNO",
Keyfeatures:" ",
space: " MEMORY: 8GB 1GB RAM",
camera: " CAMERA: 5MP 2MP front",
OS: "OPERATING SYSTEM: Android 8.1",
processor: " PROCESSOR: 1.3GHz",
dimensions: " DIMENSION: 145 x 74.2 x 9.7 mm",
others: " ",
battery: " BATTERY: 2000mAh",
inCart: false,
count:0,
total:0
},
{
id:12,
title: "TECNO POP 2F",
img:"img/tecno-pop2f.jpg",
price:23000,
company: "TECNO",
Keyfeatures:"DISPLAY: 5.45inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP 8MP front",
OS: "OPERATING SYSTEM: Android 8.1",
processor: " PROCESSOR: 1.3GHz Quad-core",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 2400mAh",
inCart: false,
count:0,
total:0
},
{
id:13,
title: "TECNO POP 2PLUS",
img:"img/tecno-pop2-plus.jpg",
price:31800,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.0inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP 8MP front",
OS: "OPERATING SYSTEM: Android 8.1",
processor: " PROCESSOR: 1.3GHz Quad processor",
dimensions: " DIMENSION: 161.7 x 78.9 x 9.55mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:14,
title: "TECNO POP 3",
img:"img/tecno-pop3.jpg",
price:26700,
company: "TECNO",
Keyfeatures:"DIPSLAY: 5.7inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP 8MP front",
OS: "OPERATING SYSTEM: Android 8.1",
processor: " PROCESSOR: 1.3GHz Quad-core",
dimensions: " DIMENSION: 154.3 x 75.4 x 9.95mm",
others: " OTHERS: fingerprint (rear) and face unlock",
battery: " BATTERY: 3500mAh",
inCart: false,
count:0,
total:0
},
{
id:15,
title: "POUVOIR 3 AIR",
img:"img/tecno-pouvoir-3-air.jpg",
price:34000,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.0inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 8MP 8MP front",
OS: "OPERATING SYSTEM: Android 9",
processor: " PROCESSOR: 2.0 GHz Quad-core",
dimensions: " DIMENSION: 163 x 78.18 x 9.25mm",
others: " OTHERS: fingerprint (rear) face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:16,
title: "TECNO SPARK 5",
img:"img/tecno-spark-5.jpg",
price:51000,
company: "TECNO",
Keyfeatures:"DISPLAY:6.6inches",
space: " MEMORY: 32GB 2GB mAh",
camera: " CAMERA:  13MP+2MP+2MP+AI Lens 8MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: 2.0GHz Quad-core",
dimensions: " DIMENSION: 164.7 x 76.3 x 8.75 mm",
others: " OTHERS: fingerprint (rear) and face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:17,
title: "TECNO SPARK 5 AIR",
img:"img/tecno-spark-5-air.jpg",
price:48500,
company: "TECNO",
Keyfeatures:"DISPLAY: 7.0inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP+AI Lens  8MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: 2.0GHz Quad-core",
dimensions: " DIMENSION: 174.64 x 79.27 x 9.05 mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:18,
title: "TECNO SPARK 4",
img:"img/Tecno-spark-4.png",
price:43500,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.52inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP+2MP+QVGA 8MP front",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Quad-core 2.0GHz",
dimensions: " DIMENSION: 165.28 x 75.9 x 8.2mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:19,
title: "TECNO CAMON 12",
img:"img/Tecno-Camon-12.jpg",
price:58500,
company: "TECNO",
Keyfeatures:" DISPLAY: 6.52inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: REAR: 16MP+2MP+8MP FRONT(Selfies): 16MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Octa-core 2.0GHz",
dimensions: " DIMENSION: 165.97 x 75.8 x 8.2mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:20,
title: "TECNO CAMON 12 AIR",
img:"img/tecno-camon-12-air.jpg",
price:53000,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.55inch",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 16MP+2MP+5MP 8MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Octa-core 2.0 GHz",
dimensions: " DIMENSION: 164.2 x 76.1 x 8.15mm",
others: " OTHERS: fingerprint (rear) and face unlock",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:21,
title: "TECNO CAMON 12 PRO",
img:"img/tecno-camon-12pro.jpg",
price:72000,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.35inches",
space: " MEMORY: RAM: 6GB ROM: 64GB 6GB RAM",
camera: " CAMERA: 16MP+2MP+8MP 32MP front",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Octa-core 2.0GHz",
dimensions: " DIMENSION: 158.6 x 75.5 x 7.8 mm",
others: " OTHERS: InScreen fingerprint and face unlock",
battery: " BATTERY: 3500mAh",
inCart: false,
count:0,
total:0
},
{
id:22,
title: "TECNO CAMON 15",
img:"img/tecno-camon-15-pro.jpg",
price:67500,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.6inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 48MP+2MP+2MP+AI Lens 16MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Octa-core 2.0GHz",
dimensions: " DIMENSION: 164.08 x 76.35 x 8.75mm",
others: " OTHERS: fingerprint (rear) face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:23,
title: "TECNO CAMON 15 AIR",
img:"img/tecno-camon-15-air.png",
price:61800,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.6inches",
space: " MEMORY: 64GB 3GB RAM",
camera: " CAMERA: 48MP+2MP+2MP+AI Lens 8MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Octa-core (1.8 GHz and 1.5GHz)",
dimensions: " DIMENSION: 164.5 x 76.5 x 8.95 mm",
others: " OTHERS: fingerprint (rear) and face unlock",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:24,
title: "TECNO CAMON 15 PREMIER",
img:"img/tecno-camon-15-premier.jpg",
price:103000,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.6inches",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 64MP+2MP+5MP+AI Lens  32MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Octa-core 2.35GHz",
dimensions: " DIMENSION: 163.3 x 77.7 x 9.05mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:25,
title: "TECNO POUVOIR 4",
img:"img/Tecno-Pouvoir-4.jpg",
price:55500,
company: "TECNO",
Keyfeatures:"DISPLAY: 7.0inches",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP+2MP+AI Lens  8MP front",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: 2.0GHz Octa-core",
dimensions: " DIMENSION: 174.9 x 79.6 x 9.2mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 6000mAh",
inCart: false,
count:0,
total:0
},
{
id:26,
title: "TECNO POUVOIR 4 PRO",
img:"img/tecno-pouvoir-4-pro.jpg",
price:65500,
company: "TECNO",
Keyfeatures:"DISPLAY: 7.0inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 16MP+2MP+5MP+AI Lens FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: 2.0GHz Quad-core",
dimensions: " DIMENSION: 174.9 x 79.6 x 9.2mm",
others: " OTHERS: fingerprint (rear) and face unlock",
battery: " BATTERY: 6000mAh",
inCart: false,
count:0,
total:0
},
{
id:27,
title: "TECNO POUVOIR 3 PLUS",
img:"img/tecno-pouvuir-3-plus.png",
price:62000,
company: "TECNO",
Keyfeatures:"DISPLAY: 6.35inches",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 13MP+2MP+8MP FRONT- 13MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: 2.0GHz Octa-core",
dimensions: " DIMENSION: 158.96 x 75.98 x 9.17mm",
others: " OTHERS: fingerprint(rear) and face unlock",
battery: " BATTERY: 6000mAh",
inCart: false,
count:0,
total:0
},
{
id:28,
title: "TECNO DROIPAD 10D",
img:"img/tecno-droipad-10d.jpg",
price:76000,
company: "TECNO",
Keyfeatures:"DISPLAY: 10.1inches",
space: " MEMORY: 16GB 2GB RAM",
camera: " CAMERA: 2MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 7",
processor: " ",
dimensions: " ",
others: "  ",
battery: " BATTERY: 7000mAh",
inCart: false,
count:0,
total:0
},
{
id:29,
title: "TECNO DROIPAD 7F",
img:"img/tecno-droipad-7f.jpg",
price:42000,
company: "TECNO",
Keyfeatures:"DISPLAY: 7.0inchesh",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 2MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 8.1",
processor: " PROCESSOR: Octa-core 1.4GHz",
dimensions: " DIMENSION: 193 x 104 x 9.6mm",
others: " OTHERS: face unlock",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:30,
title: "INFINIX NOTE 7",
img:"img/infinix-note7-1.jpg",
price:87700,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.95inch HD + Infinity-O",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 48MP+16MP+2MP+2MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 10.0",
processor: " PROCESSOR: Octa-core(2.0GHz) Mediatek helio G70(12nm)",
dimensions: " DIMENSION: 173.4 x 79 x 8.75 mm",
others: " OTHERS: side mounted fingerprint",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:31,
title: "INFINIX NOTE 7 LITE",
img:"img/infinix-note7lite.jpg",
price:75500,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inch 3Dbody",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 48MP+2MP+2MP+QVGA FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 10.0",
processor: " PROCESSOR: Octa-core (2.0GHz frequency) MTK P22",
dimensions: " DIMENSION: 165 x 76.8 x 8.7 mm",
others: " OTHERS: side mounted fingerprint",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:32,
title: "INFINIX S5 PRO",
img:"img/infinix-s5-pro.jpg",
price:93000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.53inches FHD+",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 48MP+2MP+QVGA FRONT- 40MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 162.5 x 76.88x 8.95 mm",
others: "  ",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:33,
title: "INFINIX S5 PRO",
img:"img/infinix-s5-pro.jpg",
price:76600,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.53inches FHD+ ",
space: " MEMORY:  4GB RAM",
camera: " CAMERA: 48MP+2MP+QVGA FRONT- 40MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Octa-core 2.3GHz frequency MTK 6762 Helio P35",
dimensions: " DIMENSION: 162.5 x 76.88 x 8.95mm",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:34,
title: "INFINIX S5",
img:"img/infinix-s5.jpg",
price:80000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches HD+ Infinity-O",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 16MP+5MP+2MP+QVGA FRONT- 32MP",
processor: " PROCESSOR: Octa-core 2.0GHz frequency MTK 6762 Helio P22",
dimensions: " DIMENSION: 164 x 76 x 7.9 mm",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:35,
title: "INFINIX S5 LITE",
img:"img/infinix-s5-lite.jpg",
price:60000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches HD+ Infinity-O",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 16MP+2MP+QVGA FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Octa-core 2.0GHz frequency MTK 6761 P22 ",
dimensions: " DIMENSION: 164 x 76 x 7.9",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:36,
title: "INFINIX S5 LITE",
img:"img/infinix-s5-lite.jpg",
price:55000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches HD+ Infinity-O",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 16MP+2MP+QVGA FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Octa-core 2.0GHz frequency MTK 6761 P22",
dimensions: " DIMENSION: 164 x76 x 7.9",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:37,
title: "INFINIX HOT 9",
img:"img/infinix-hot9.jpg",
price:53500,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches HD+Infinity-O ",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 16MP+2MP+2MP+AI Lens FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: MT6762D Octa-core",
dimensions: " DIMENSION: 165.4 x 76.8 x 8.75 mm",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:38,
title: "INFINIX HOT 9 PLAY",
img:"img/infinix-hot-9-play.jpg",
price:51200,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.82inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA:  13MP Dual camera FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 171.8 x 77.96 x 8.90 mm",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 6000mAh",
inCart: false,
count:0,
total:0
},
{
id:39,
title: "INFINIX HOT 8",
img:"img/infinix-hot8.jpg",
price:51000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inch + WaterDrop Display",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP+QVGA AF With Quad Flashlight FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), Xos 5.0",
processor: " PROCESSOR: Mediatek MT6761 Hello A22(12 nm)",
dimensions: " DIMENSION: 165 x 76.3 x 8.7 mm",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:40,
title: "INFINIX HOT 8",
img:"img/infinix-hot8.jpg",
price:47500,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.52inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP+2MP+QVGA FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), Xos 5.0",
processor: " PROCESSOR: Mediatek MT6761 Hello A22(12 nm)",
dimensions: " DIMENSION: 165 x 76.3 x 8.7 mm",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:41,
title: "INFINIX HOT 8 LITE",
img:"img/infinix-hot-8-lite.jpg",
price:42500,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches", 
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP Dual camera FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Mediatek MT6761 Hello A22(12 nm)",
dimensions: " DIMENSION: 165 x 76.3 x 8.7 mm",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:42,
title: "INFINIX SMART 4",
img:"img/infinix-smart4.jpg",
price:38000,
company: "INFINIX",
Keyfeatures:"DISPLAY: 6.6inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Quad-core2.0GHz MTK 6761 Helio A22",
dimensions: " DIMENSION: 167 x 76 x 8.3mm",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:43,
title: "OPPO A9 2020",
img:"img/OppoA9 2020.jpg",
price:103000,
company: "OPPO",
Keyfeatures:"DISPLAY: 6.5inches",
space: " MEMORY: 128GB 8GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP FRONT- 32MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), ColorOS 6.1",
processor: " PROCESSOR: Octa-core(4x2.0 GHz Kyryo 260 Gold & 4x1.8 GHz Kyro 260 Silver)",
dimensions: " DIMENSION: 163.6 x 75.6 x 9.1 mm",
others: " OTHERS: fingerprint(rear-mounted), microUSB 2.0 USB ",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:44,
title: "OPPO A31",
img:"img/oppoA31.jpg",
price:83900,
company: "OPPO",
Keyfeatures:"DISPLAY: 6.5inches Waterdrop Screen",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 12MP+2MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0, ColorOS 6.1",
processor: " PROCESSOR: 2.3GHz Octa-Core Processor",
dimensions: " DIMENSION: 163.9 x 75.5 x 8.3 mm",
others: " OTHERS: fingerprint",
battery: " BATTERY: 4230mAh",
inCart: false,
count:0,
total:0
},
{
id:45,
title: "OPPO A1k",
img:"img/oppoA1k.jpg",
price:49900,
company: "OPPO",
Keyfeatures:"DISPLAY: 6.1inches HD+",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9.0, ColorOS 6",
processor: " PROCESSOR: Octa-core, up to 2.0GHz",
dimensions: " DIMENSION: 154.5 x 73.8 x 8.4 mm",
others: " ",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:46,
title: "OPPO RENO 3",
img:"img/oppo-reno3.jpg",
price:159000,
company: "OPPO",
Keyfeatures:"DISPLAY:6.4inches Waterdrop",
space: " MEMORY: 128GB 8GB RAM",
camera: " CAMERA: 48MP+13MP+8MP+2MP FRONT- 44MP",
OS: "OPERATING SYSTEM: Android 10",
processor: " PROCESSOR: Octa-core MediaTek Helio P90 (MT6779)",
dimensions: " DIMENSION: 160.20 x 73.30 x 7.90",
others: " OTHERS: TOUCH SCREEN",
battery: " BATTERY: 4025mAh",
inCart: false,
count:0,
total:0
},
{
id:47,
title: "OPPO A12",
img:"img/oppoa12.jpg",
price:59900,
company: "OPPO",
Keyfeatures:"DISPLAY: 6.22inches Waterdrop",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9",
processor: " PROCESSOR: ",
dimensions: " DIMENSION: ",
others: " OTHERS: fingerprint sensor",
battery: " BATTERY: 4230mAh",
inCart: false,
count:0,
total:0
},
{
id:48,
title: "OPPO A31",
img:"img/oppoa31.jpg",
price:69900,
company: "OPPO",
Keyfeatures:"DISPLAY: 6.5inches Waterdrop",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 12MP+2MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: ColorOS 6.1 (Based on Android 9.0)",
processor: " PROCESSOR: 2.3GHz Octa-Core",
dimensions: " DIMENSION: 163.9 x 75.5 x 8.3 mm",
others: " OTHERS: fingerprint(rear-mounted)",
battery: " BATTERY: 4230mAh",
inCart: false,
count:0,
total:0
},
{
id:49,
title: "HUAWEI Y9S",
img:"img/y9s.jpg",
price:108900,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 6.59inches",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 48MP+8MP+2MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9(Pie)",
processor: " PROCESSOR: ",
dimensions: " DIMENSION: 163.1 x 77.2 x 8.8 mm",
others: " OTHERS: side mounted fingerprint, type C",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:50,
title: "HUAWEI Y9 PRIME 2019",
img:"img/Y9-prime.jpg",
price:94500,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 6.59inches",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 16MP+8MP+2MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9, EMUI 9.0",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 163.5 x 77.3 x 8.8 mm",
others: " OTHERS: fingerprinter sensor,ambient light sensor, digital compass",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:51,
title: "HUAWEI Y7 PRO",
img:"img/Y7-pro.jpg",
price:69900,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 6.39inches LCD",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 48MP+8MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: EMUI 9.1(Based on Android 9)",
processor: " PROCESSOR: NULL",
dimensions: " DIMENSION: 159.81 x 76.13 x 8.13 mm",
others: " OTHERS: fingerprinter sensor,ambient light sensor, digital compass",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:52,
title: "HUAWEI Y7",
img:"img/Y7.jpg",
price:61500,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 6.26inches",
space: " MEMORY: 64GB 3GB RAM",
camera: " CAMERA: 13MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 8.1 (Oreo), EMUI 8.2",
processor: " PROCESSOR: Octa-core 1.8 GHz Cortex-A53",
dimensions: " DIMENSION: 158.9 x 76.9 x 8.1 mm",
others: " OTHERS: fingerprinter(rear-mounted),ambient light sensor, digital compass",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:53,
title: "HUAWEI Y7",
img:"img/Y7.jpg",
price:59900,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 6.26inches 3GB RAM 32GB ROM 13MP 4000mAh",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 8.1 (Oreo), EMUI 8.2",
processor: " PROCESSOR: Octa-core 1.8 GHz Cortex-A53",
dimensions: " DIMENSION: 158.9 x 76.9 x 8.1 mm",
others: " OTHERS: fingerprinter(rear-mounted),ambient light sensor, digital compass",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:54,
title: "HUAWEI Y6",
img:"img/Y6.jpg",
price:51900,
company: "HUAWEI",
Keyfeatures: "DISPLAY: 6.09inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0 (Pie), EMUI 9.1",
processor: " PROCESSOR: Quad-core 2.0 GHz Cortex-A53",
dimensions: " DIMENSION: 156.3 x 73.5 x 8 mm",
others: " OTHERS: fingerprint(rear-mounted), microUSB 2.0",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:55,
title: "HUAWEI Y5",
img:"img/Y5.jpg",
price:36000,
company: "HUAWEI",
Keyfeatures:"DISPLAY: 5.75inches",
space: " MEMORY: 16GB  2GB RAM",
camera: " CAMERA: 13MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9.0 (Pie), EMUI 9.1",
processor: " PROCESSOR: NULL",
dimensions: " DIMENSION: 147.1 x 70.8 x 8.5 mm",
others: " OTHERS: microUSB 2.0",
battery: " BATTERY: 3020mAh",
inCart: false,
count:0,
total:0
},
{
id:56,
title: "XIAOMI REDMI NOTE 8",
img:"img/redmi-note-8.jpg",
price:75000,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP FRONT- 13MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core (4x2.0 GHz Kryo 260 Gold & 4x1.8 GHz Kryo 260 Silver)",
dimensions: " DIMENSION: 158.3 x 75.3 x 8.4 mm",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:57,
title: "XIAOMI REDMI NOTE 8",
img:"img/redmi-note-8.jpg",
price:62500,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP FRONT- 13MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core (4x2.0 GHz Kryo 260 Gold & 4x1.8 GHz Kryo 260 Silver)",
dimensions: " DIMENSION: 158.3 x 75.3 x 8.4 mm",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:58,
title: "XIAOMI REDMI NOTE 8",
img:"img/redmi-note-8.jpg",
price:88000,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP FRONT- 13MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core (4x2.0 GHz Kryo 260 Gold & 4x1.8 GHz Kryo 260 Silver)",
dimensions: " DIMENSION: 158.3 x 75.3 x 8.4 mm",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:59,
title: "XIAOMI REDMI NOTE 8 PRO",
img:"img/redmi-note-8-pro.jpg",
price:103000,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 64MP+8MP+2MP+2MP FRONT- 20MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core (Media tek helio G901)",
dimensions: " DIMENSION:  ",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4500mAh",
inCart: false,
count:0,
total:0
},
{
id:60,
title: "XIAOMI REDMI NOTE 8 PRO",
img:"img/redmi-note-8-pro.jpg",
price:94000,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 64GB 6GB RAM",
camera: " CAMERA: 64MP+8MP+2MP+2MP FRONT- 20MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core (Media tek helio G901)",
dimensions: " DIMENSION:  ",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 4500mAh",
inCart: false,
count:0,
total:0
},
{
id:61,
title: "XIAOMI REDMI 8",
img:"img/redmi-8.jpg",
price:56200,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 12MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Qual comm Snapdragon439",
dimensions: " DIMENSION: ",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:62,
title: "XIAOMI REDMI 8",
img:"img/redmi-8.jpg",
price:53200,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 12MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Qual comm Snapdragon439",
dimensions: " DIMENSION: ",
others: " OTHERS: fingerprint(rear-mounted) 2.0, type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:63,
title: "XIAOMI REDMI 8A",
img:"img/redmi-8a.jpg",
price:45200,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.3inches Waterdrop",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 12MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Qual Comm Snapdragon 439",
dimensions: "  ",
others: " OTHERS: face unlock,  type-C 1.0 reversible connector",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:64,
title: "XIAOMI REDMI NOTE 9S",
img:"img/redmi-note-9-s.jpg",
price:94700,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.67inches Dot",
space: " MEMORY: 128GB 6GB RAM",
camera: " CAMERA: 48MP+8MP+5MP+2MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core 2.3GHz Qual comm Snapdragon 720",
dimensions: " DIMENSION: 158.3 x 75.3 x 8.4 mm",
others: " OTHERS: side fingerprint sensor, type-C",
battery: " BATTERY: 5020mAh",
inCart: false,
count:0,
total:0
},
{
id:65,
title: "XIAOMI REDMI NOTE 9S",
img:"img/redmi-note-9-s.jpg",
price:86200,
company: "XIAOMI REDMI",
Keyfeatures:"DISPLAY: 6.67inches Dot",
space: " MEMORY: 64GB 6GB RAM",
camera: " CAMERA: 48MP+8MP+5MP+2MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), MIUI 11",
processor: " PROCESSOR: Octa-core 2.3GHz Qual comm Snapdragon 720",
dimensions: " DIMENSION: 158.3 x 75.3 x 8.4 mm",
others: " OTHERS: side fingerprint sensor, type-C",
battery: " BATTERY: 5020mAh",
inCart: false,
count:0,
total:0
},
{
id:66,
title: "GIONEE M11",
img:"img/gionee-m11.jpg",
price:50000,
company: "GIONEE",
Keyfeatures:"DISPLAY: 6.3inches FHD+Waterdrop screen 2.5D curved glass back cover",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 16MP+5MP FRONT- 13MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie)",
processor: " PROCESSOR: Octa-core 2.0GHz",
dimensions: " ",
others: " OTHERS: Rear fingerprint scanner, type C",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:67,
title: "GIONEE S11",
img:"img/gionee-s11.jpg",
price:40000,
company: "GIONEE",
Keyfeatures:"DISPLAY: 5.99inches",
space: " MEMORY: 32GB 4GB RAM",
camera: " CAMERA: 16MP+5MP FRONT- 16MP+8MP",
OS: "OPERATING SYSTEM: Android 7.1 (Nougat), Amigo 5.0",
processor: " PROCESSOR: Octa-core Mediatek MT6763T Helio P23 CPU",
dimensions: " DIMENSION: NULL",
others: " OTHERS: fingerprint scanner(rear)",
battery: " BATTERY: 3410mAh",
inCart: false,
count:0,
total:0
},
{
id:68,
title: "GIONEE X2",
img:"img/gionee-x2.jpeg",
price:37500,
company: "GIONEE",
Keyfeatures:"DISPLAY: 6.088inches HD Waterdrop",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie)",
processor: " PROCESSOR: MT6761 Quad core 2.0GHz",
dimensions: " ",
others: " OTHERS: fiingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:69,
title: "GIONEE P10 M",
img:"img/gionee-p10m.jpg",
price:27500,
company: "GIONEE",
Keyfeatures:"DISPLAY: 6.088inches HD Waterdrop full screen display",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 8.1(oreo) Go Edition",
processor: " PROCESSOR: MT6580A Quad core 1.3GHz",
dimensions: " DIMENSION: NULL",
others: " OTHERS: fingerprint (rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:70,
title: "GIONEE M6 LITE",
img:"img/gionee-m6lite.jpeg",
price:20500,
company: "GIONEE",
Keyfeatures:"DISPLAY: 5.0inches HD Waterdrop full screen",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 13MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 6.0 Marshmallow",
processor: " PROCESSOR: MediaTek Helio P10 MT6755",
dimensions: " DIMENSION: 152.3 x 75.3 x 8.2 mm",
others: " OTHERS: Proximity Sensor",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:71,
title: "IMOSE X-1 PRO",
img:"img/Imose-X-1-Pro.jpg",
price:28500,
company: "IMOSE",
Keyfeatures:"DISPLAY: 7.0inches touch ",
space: " MEMORY: 8GB 1GB RAM",
camera: " CAMERA: 5MP FRONT- 1.3MP",
OS: "OPERATING SYSTEM: Android 4.4.2 kikkat",
processor: " PROCESSOR: 1.3GHz quad-core ",
dimensions: " ",
others: " ",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:72,
title: "IMOSE GIDI PLUS",
img:"img/imose-Gidi-Plus.jpg",
price:18000,
company: "IMOSE",
Keyfeatures:"DISPLAY: 5.5inches Incell infinity",
space: " MEMORY: 8GB 1G RAM",
camera: " CAMERA: 16MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: 1.3GHz quad-core",
dimensions: " DIMENSION: 145.5 x 70.7 x 9.2 mm",
others: " OTHERS: fingerprint(rear), face Unlock",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:73,
title: "IMOSE OMOTAB 3S KIDS TAB",
img:"img/omotab-3s3s.jpg",
price:28000,
company: "IMOSE",
Keyfeatures:"DISPLAY: 7.0inches HD",
space: " MEMORY: 8GB 1G RAM",
camera: " CAMERA: VGA",
OS: "OPERATING SYSTEM: Android Nougat 7.0",
processor: " ",
dimensions: " ",
others: " ",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:74,
title: "IMOSE OMOTAB KIDS TAB",
img:"img/omotabwithhandle.jpg",
price:26000,
company: "IMOSE",
Keyfeatures:"DISPLAY: 7.0inches",
space: " MEMORY: 8GB 1GB RAM",
camera: " CAMERA: VGA",
OS: "OPERATING SYSTEM: Android Nougat 7.0",
processor: " ",
dimensions: " ",
others: " ",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:75,
title: "ITEL A56 PRO",
img:"img/itel-a56-pro.jpg",
price:34000,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.0inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: "  ",
dimensions: " ",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:76,
title: "ITEL A56",
img:"img/itel-a56.jpg",
price:28000,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.0inches",
space: " MEMORY:  16GB 1GB RAM",
camera: " CAMERA:  8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " ",
dimensions: " ",
others: " OTHERS: fingerprint(rear)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:77,
title: " ITEL A36",
img:"img/itel A36.png",
price:33500,
company: "ITEL",
Keyfeatures:"DISPLAY: 5.5inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA:  5MP",
OS: " ",
processor: " ",
dimensions: " ",
others: " ",
battery: " BATTERY: 3020mAh",
inCart: false,
count:0,
total:0
},
{
id:78,
title: "ITEL P33 PLUS",
img:"img/itel-p33-plus.jpg",
price:31000,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.0inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 8MP+0.8MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 8.1 Oreo",
processor: " PROCESSOR: Quad-core MediaTek MT6580",
dimensions: " ",
others: " ",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:79,
title: "ITEL S15 PRO",
img:"img/itel-s15-pro.jpg",
price:38500,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.1inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 8MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0 (Pie)",
processor: " PROCESSOR: Quad Core 1.6 GHz",
dimensions: " DIMENSION: 157.2 x 76.25 x 8.05 mm",
others: "  ",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:80,
title: "ITEL S15",
img:"img/itel-s15.jpg",
price:31000,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.1inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 8MP+8MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Quad-core Spreadtrum Unisoc SC7731E",
dimensions: " ",
others: " OTHERS: fingerprint sensor",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:81,
title: "ITEL S15",
img:"img/itel-s15.jpg",
price:34500,
company: "ITEL",
Keyfeatures:"DISPLAY: 6.1inches",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 8MP+8MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0",
processor: " PROCESSOR: Quad-core Spreadtrum Unisoc SC7731E",
dimensions: " ",
others: " OTHERS: fingerprint sensor",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:82,
title: "ITEL A33",
img:"img/itel-A33.jpeg",
price:21500,
company: "ITEL",
Keyfeatures:"DISPLAY: 5.0inches",
space: " MEMORY: 8GB 1GB RAM",
camera: " CAMERA: 5MP FRONT- 2MP",
OS: "OPERATING SYSTEM: Android 8.1 Oreo",
processor: " PROCESSOR: Quad-core MediaTek MT6580",
dimensions: " ",
others: " ",
battery: " BATTERY: 2200mAh",
inCart: false,
count:0,
total:0
},
{
id:83,
title: "ITEL P15",
img:"img/itel-p15.jpg",
price:23500,
company: "ITEL",
Keyfeatures:"DISPLAY: 5.0inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP FRONT- 2MP",
OS: "OPERATING SYSTEM: Android 9",
processor: " PROCESSOR: Quad-core 1.3 GHz Cortex-A7 (32nm)",
dimensions: " DIMENSION: 136.7 x 68 x 8.3 mm",
others: " OTHERS: fingerprint(rear-mounted)",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:84,
title: "ITEL A16 PLUS",
img:"img/itel-a16plus.jpg",
price:19000,
company: "ITEL",
Keyfeatures:"DISPLAY: 5.0inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP FRONT- 2MP",
OS: " ",
processor: "  ",
dimensions: "  ",
others: "  ",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
},
{
id:85,
title: "ITEL A14",
img:"img/itel-a14.jpg",
price:15500,
company: "ITEL",
Keyfeatures:" ",
space: " MEMORY: 8GB 512MB RAM",
camera: " ",
OS: " ",
processor: "  ",
dimensions: "  ",
others: " ",
battery: " BATTERY: 1500mAh",
inCart: false,
count:0,
total:0
},
{
id:86,
title: "VIVO Y11",
img:"img/vivo-Y11.jpg",
price:59900,
company: "VIVO",
Keyfeatures:"DISPLAY: 6.35inches Halo FullView",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: (based on Android 9), Funtouch OS 9.1",
processor: " PROCESSOR: SMD439 1.93GHz Octa-Core",
dimensions: " DIMENSION: 159.43 x 76.77 x 8.92 mm",
others: " OTHERS: fingerprint sensor, usb",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:87,
title: "VIVO Y12",
img:"img/vivo-Y12.jpg",
price:69900,
company: "VIVO",
Keyfeatures:"DISPLAY: 6.35inches",
space: " MEMORY: 64GB 3GB RAM",
camera: " CAMERA: 13MP+8MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), Funtouch 9",
processor: " PROCESSOR: Mediatek MT6762 Helio P22, Octa-core 2.0GHz Cortex-A53",
dimensions: " DIMENSION: 159.4 x 76.8 x 8.9 mm",
others: " OTHERS: fingerprint(rear-mounted), microUSB 2.0",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:88,
title: "VIVO Y91C",
img:"img/vivo-y91c.jpg",
price:49900,
company: "VIVO",
Keyfeatures:"DISPLAY: 6.22inches HD",
space: " MEMORY: 32GB 2GB RAM",
camera: " CAMERA: 13MP FRONT- 5MP",
OS: "OPERATING SYSTEM: Android 8.1, Funtouch 4.5",
processor: " PROCESSOR: Octa-core",
dimensions: " DIMENSION: 155.11 x 75.09 x 8.28 mm",
others: " OTHERS: NULL",
battery: " BATTERY: 4030mAh",
inCart: false,
count:0,
total:0
},
{
id:89,
title: "VIVO Y15",
img:"img/vivo-Y15.jpg",
price:72900,
company: "VIVO",
Keyfeatures:"DISPLAY: 6.35inches HD",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 13MP+8MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie), Funtouch 9",
processor: " PROCESSOR: Mediatek MT6762",
dimensions: " DIMENSION: 159.43 x 76.77 x 8.92 mm",
others: " OTHERS: fingerprint sensor",
battery: " BATTERY: 5000mAh",
inCart: false,
count:0,
total:0
},
{
id:90,
title: "VIVO V19",
img:"img/vivo-v19.jpg",
price:169900,
company: "VIVO",
Keyfeatures:"DISPLAY: 6.44inches FHD",
space: " MEMORY: 128GB 8GB RAM",
camera: " CAMERA: 48MP+8MP+2MP+2MP FRONT- 32MP+8MP",
OS: "OPERATING SYSTEM: Android 10(Pie), Funtouch OS 10",
processor: " PROCESSOR: Snapdragon 712",
dimensions: " DIMENSION: 159.64 x 75.04 x 8.5 mm",
others: " OTHERS: fingerprint(In-display), type C",
battery: " BATTERY: 4500mAh",
inCart: false,
count:0,
total:0
},
{
id:91,
title: "NOKIA 4.2",
img:"img/nokia4.2.jpg",
price:43000,
company: "NOKIA",
Keyfeatures:"DISPLAY: 5.71inches",
space: " MEMORY: 32GB 3GB RAM",
camera: " CAMERA: 13MP+2MP FRONT- 8MP",
OS: "OPERATING SYSTEM: Android 9.0 (Pie), upgradable to Android 10, Android One",
processor: " PROCESSOR: Octa-core (4x1.95 GHz Cortex-A53 & 4x1.45 GHz Cortex A53)",
dimensions: " DIMENSION: 149 x 71.3 x 8.4 mm",
others: " OTHERS: fingerprint(rear-mounted), microUSB 2.0",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:92,
title: "NOKIA C1",
img:"img/nokiaC1.jpg",
price:26000,
company: "NOKIA",
Keyfeatures:"DISPLAY: 5.45inches",
space: " MEMORY: 16GB 1GB RAM",
camera: " CAMERA: 5MP FRONT- 5MP ",
OS: "OPERATING SYSTEM: Android 9.0 Pie (Go edition)",
processor: " PROCESSOR: Quad-core 1.3 GHz",
dimensions: " DIMENSION: 147.6 x 71.4 x 8.7 mm",
others: " OTHERS: Accelerometer, microUSB 2.0",
battery: " BATTERY: 2500mAh",
inCart: false,
count:0,
total:0
},
{
id:93,
title: "OLLA M1 LITE",
img:"img/olla-m1lite.jpg",
price:20500,
company: "OLLA",
Keyfeatures:"DISPLAY: 5.7inches",
space: " MEMORY: 16GB 2GB RAM",
camera: " CAMERA: 8MP",
OS: " ",
processor: " ",
dimensions: " ",
others: " ",
battery: " BATTERY: 3000mAh",
inCart: false,
count:0,
total:0
},
{
id:94,
title: "OLLA M6",
img:"img/olla-m6.png",
price:16000,
company: "OLLA",
Keyfeatures:"DISPLAY: 5.4inches",
space: " MEMORY: 8GB 1GB RAM",
camera: " CAMERA: 5MP",
OS: " ",
processor: " ",
dimensions: " ",
others: " ",
battery: " BATTERY: 2500mAh",
inCart: false,
count:0,
total:0
},
{
id:95,
title: "OLLA NOTE 3",
img:"img/olla-note3.jpg",
price:56000,
company: "OLLA",
Keyfeatures:"DISPLAY: 6.5inches IPS LCD",
space: " MEMORY: 64GB 4GB RAM",
camera: " CAMERA: 16MP FRONT- 16MP",
OS: "OPERATING SYSTEM: Android 9.0(Pie)",
processor: " PROCESSOR: Octa-core mediatek MT 6763",
dimensions: " ",
others: " OTHERS: fingerprint rear mounted",
battery: " BATTERY: 3300mAh",
inCart: false,
count:0,
total:0
}
 ];
 export const detailProduct = {
id:1,
title: "Samsung Galaxy A51",
img:"img/samsung-Galaxy-A51-2.jpg",
price: 125200,
company: "SAMSUNG",
Keyfeatures: " DISPLAY: 6.5inches FHD+(1080 x 2400)sAMOLED",
space: " MEMORY: 128GB 4GB RAM",
camera: " CAMERA: 48MP+12MP+5MP+5MP 32MP front",
OS: "OPERATING SYSTEM: Android 10, One UI 2.1",
processor: " PROCESSOR: Exynos 9611 (Quad 2.3GHz + Quad1.7GHz)",
dimensions: " DIMENSION: 158.5 x 73.6 x 7.9 mm",
others: " OTHERS: On-screen fingerprint, c-type fast charging, bixby",
battery: " BATTERY: 4000mAh",
inCart: false,
count:0,
total:0
    }

    
